inputs:
  authToken:
    description: Auth token for private GPR access
runs:
  using: composite
  steps:
    - name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-

    - name: Setup NodeJS
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies & test
      shell: bash
      run: |
        echo "//npm.pkg.github.com/:_authToken=$NODE_AUTH_TOKEN" >> ~/.npmrc
        npm cit
      env:
        NODE_AUTH_TOKEN: ${{ inputs.authToken }}

    - name: Audit dependencies
      shell: bash
      run: npm audit --audit-level=critical

    - name: Lint
      shell: bash
      run: npm run lint --if-present
