inputs:
  accountIds:
    description: JSON for linked account IDs
    default: $JSON_AWS_ACCOUNT_IDS
runs:
  using: composite
  steps:
    - name: Determine Credentials
      shell: bash
      run: |
        if echo ${{ github.ref }} | grep -q "refs/heads/master"
        then
          export AWS_ACCOUNT_TARGET=production
        else
          export AWS_ACCOUNT_TARGET=development
        fi

        echo "aws account target is $AWS_ACCOUNT_TARGET"

        AWS_ACCOUNT_ID=`echo '${{ inputs.accountIds }}' | jq -r ".$AWS_ACCOUNT_TARGET"`

        aws sts assume-role --role-arn arn:aws:iam::$AWS_ACCOUNT_ID:role/CI --external-id $AWS_EXTERNAL_ID --role-session-name "$AWS_ROLE_SESSION_NAME" --output json --query 'Credentials' > credentials.json

        echo "AWS_ACCESS_KEY_ID=`cat credentials.json | jq -r '.AccessKeyId'`" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=`cat credentials.json | jq -r '.SecretAccessKey'`" >> $GITHUB_ENV
        echo "AWS_SESSION_TOKEN=`cat credentials.json | jq -r '.SessionToken'`" >> $GITHUB_ENV
